version: 2

builds:
  - id: detonate
    binary: detonate
    main: ./cmd/detonate
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/m4vic/detonate/internal/cli.Version={{.Version}} -X github.com/m4vic/detonate/internal/cli.Commit={{.Commit}}

archives:
  - id: detonate-archive
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incminor .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: m4vic
    name: detonate
